# Databricks App Configuration
# WeCom Feedback Collection System

name: wecomfb
description: WeCom Feedback Collection System

command:
  - "bash"
  - "-c"
  - |
    set -e
    echo "Starting WeCom Feedback Collection System..."
    echo "Working directory: $(pwd)"
    ls -la
    
    # Set PYTHONPATH
    export PYTHONPATH="$(pwd):${PYTHONPATH:-}"
    echo "PYTHONPATH: ${PYTHONPATH}"
    
    # Install dependencies
    if [ -f "requirements.txt" ]; then
      echo "Installing dependencies..."
      pip install --quiet --no-cache-dir -r requirements.txt
    fi
    
    # Use PORT environment variable set by Databricks (default to 8080 if not set)
    APP_PORT="${PORT:-8080}"
    echo "Starting API service on port ${APP_PORT}..."
    
    exec gunicorn databricks_app.api_app:app \
      --bind 0.0.0.0:${APP_PORT} \
      --workers 2 \
      --timeout 120 \
      --access-logfile - \
      --error-logfile -

env:
  # All other env vars are loaded from .env file via load_dotenv()
  # Only keep secrets that should not be committed to repo
  - name: WEBHOOK_SECRET
    value: "{{secrets/feedback-scope/webhook-secret}}"
  
  # Storage Configuration
  - name: STORAGE_BACKEND
    value: "uc"
  - name: UC_CATALOG
    value: "causalab_dev"
  - name: UC_SCHEMA
    value: "inner_feedback"
  - name: TABLE_NAME
    value: "player_feedback"
  
  # Databricks Connection
  - name: DATABRICKS_HOST
    value: "https://dbc-235982e0-d861.cloud.databricks.com/"
  - name: DATABRICKS_TOKEN
    value: "{{secrets/feedback-scope/databricks-token}}"
  
  # WeCom Bot Configuration
  - name: WECOM_CORP_ID
    value: "{{secrets/feedback-scope/wecom-corp-id}}"
  - name: WECOM_TOKEN
    value: "{{secrets/feedback-scope/wecom-token}}"
  - name: WECOM_ENCODING_AES_KEY
    value: "{{secrets/feedback-scope/wecom-aes-key}}"
  - name: WECOM_BOT_WEBHOOK
    value: "{{secrets/feedback-scope/wecom-webhook}}"

resources:
  cpu: "2"
  memory: "4Gi"

health:
  path: "/health"
  interval: 30
